#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT_DIR = path.resolve(__dirname, '..')
const outputPath = path.join(ROOT_DIR, 'src', 'env.ts')

function getMode(argv) {
  const modeIndex = argv.findIndex((arg) => arg === '--mode')
  if (modeIndex === -1) return 'prod'
  const mode = argv[modeIndex + 1]
  if (mode !== 'dev' && mode !== 'prod') {
    throw new Error(`Invalid --mode value "${mode}". Expected "dev" or "prod".`)
  }
  return mode
}

const mode = getMode(process.argv.slice(2))
const envValue = mode === 'dev' ? 'development' : 'production'

const fileContent = `// This file is generated by scripts/generate-env.mjs.
// Do not edit manually.
const ENV: 'development' | 'production' = '${envValue}'
export default ENV
`

fs.writeFileSync(outputPath, fileContent, 'utf8')
console.log(`Generated src/env.ts (${envValue})`)
