// This file is generated by scripts/generate-socket-config.mjs.
// Do not edit manually.
export const SOCKET_CONFIG = {
  mode: 'prod',
  paths: {
    windows: '\\\\.\\pipe\\quill_mcp',
    darwin: '/tmp/quill_mcp.sock',
  },
} as const
